schema_version = 1

[upstream_state]
platform = "curseforge"
project_id = "1373378"
version = "FTB StoneBlock 4 1.13.1"
artifact_id = "8079634"
artifact_kind = "curseforge_file"
primary_file_name = "ftb-stoneblock-4-1.13.1.zip"
fetched_at = "2026-05-17T13:27:03Z"
source_archive_sha256 = "cfec316b52d9d019a2c818290eb3ed1c1c79ddcf873aff22b4894f9c316ded79"
